/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeape;

import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author deeghayuadhikari
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    ResultSet Rs = null,Rs1 = null,Rs2 = null;
    Connection Con = null, Con2 = null, Con3 = null;
    Statement St = null, St1 = null, St2 = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Login1 = new javax.swing.JButton();
        Reset1 = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Nasa", 0, 48)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("COST CAFE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeape/coffee (2).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 242, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Hubballi", 1, 48)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COST CAFE 2.0");
        jLabel13.setToolTipText("Name of the cafe");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 320, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Due to the security reasons, Contact the it department for sign-up a new user");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 460, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/deeghayuadhikari/Desktop/2.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeape/coffee (2).png"))); // NOI18N
        jLabel2.setToolTipText("Logo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 20, 320, -1));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Login");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 160, 290, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeape/1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 410, -1));

        Password.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        Password.setToolTipText("");
        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 320, 39));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 129, -1));

        Username.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 320, 37));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 137, -1));

        Login1.setBackground(new java.awt.Color(66, 133, 234));
        Login1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        Login1.setForeground(new java.awt.Color(255, 255, 255));
        Login1.setText("Login");
        Login1.setToolTipText("Press \"ENTER\" to login after you type the password");
        Login1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 234), 2));
        Login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 140, 42));

        Reset1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        Reset1.setForeground(new java.awt.Color(90, 168, 105));
        Reset1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reset1.setText("RESET");
        Reset1.setToolTipText("Reset the Username and Password text feildsfields ");
        Reset1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 168, 105), 2));
        Reset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset1.setPreferredSize(new java.awt.Dimension(100, 30));
        Reset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset1MouseClicked(evt);
            }
        });
        jPanel1.add(Reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 140, 41));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int count_ID;
    private void countLog(){
        try{
            St1 = Con.createStatement();
            Rs1 = St1.executeQuery(" Select Max(ID) from logbook");
            Rs1.next();
            count_ID = Rs1.getInt(2)+1;
            
        } catch (Exception e){
            
        }
    }
    private void insertLogBook(){
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        
               Con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAFECOST","root","Deegayu2001");
               PreparedStatement ps2 = Con2.prepareStatement("insert into logbook values(?,?)");
               ps2.setInt(2, count_ID);
               ps2.setString(1, Username.getText());
               int row = ps2.executeUpdate();
               Con2.close();
        } catch (Exception e){

        }
    }
    int Type;
    private void gettingId(){
        try{
            St2 = Con.createStatement();
            Rs2 = St2.executeQuery(" Select ID from login where Username ='"+Username.getText()+"'");
            Rs2.next();
            Type = Rs.getInt(3);
            
        } catch (Exception e){
            
        }
    }
    String Seller;
    private void checkloging(){
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CAFECOST","root","Deegayu2001");
        String s = "select * from login where Username=? and Password=?";
        PreparedStatement ps = con.prepareStatement(s);
        ps.setString(1, Username.getText());
        ps.setString(2, Password.getText());
        //JOptionPane.showMessageDialog(this,Username.getText());
       // JOptionPane.showMessageDialog(this, Type);
        ResultSet rs = ps.executeQuery();   
             if(rs.next()){
                 Seller = Username.getText();
                 countLog();
                 insertLogBook();
                 gettingId();
                 if(Seller.equals("cashier") || Seller.equals("kasun")){
                    new BillMakerForCas().setVisible(true);
                    this.dispose(); 
                 } else if(Seller.equals("shareholder")|| Seller.equals("ashen")){
                    new HistoryForShareHolder().setVisible(true);
                    this.dispose(); 
                 } else {
                    new Items().setVisible(true);
                    this.dispose(); 
                 }
                
             }else{ 
                  JOptionPane.showMessageDialog(this,"Please check your username and password");
                  Username.setText("");
                  Password.setText("");
             }
        con.close();
        }catch(Exception e){
        
            System.out.println(e);
        
        }
    }
    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        checkloging();
    }//GEN-LAST:event_Login1ActionPerformed

    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt. getKeyCode() == KeyEvent. VK_ENTER) {
            checkloging();
        }
    }//GEN-LAST:event_PasswordKeyPressed

    private void Reset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset1MouseClicked
       Username.setText("");
                  Password.setText("");
    }//GEN-LAST:event_Reset1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Reset1;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
